from apscheduler.schedulers.background import BackgroundScheduler
import json
from datetime import date, timedelta

from app.models import Project
from app.models.ai_usage_log import AIUsageLog
from app.services.ai_service import AIServiceError, weekly_summary
from app.services.notification_service import send_notification
from app.services.payroll_service import generate_payroll_for_project
from app.extensions import db

_scheduler = None


def run_weekly_summaries_job():
    projects = Project.query.all()
    for project in projects:
        try:
            summary_data = weekly_summary(project.id)
            title = "Résumé hebdomadaire IA"
            content = summary_data.get("progression_globale") or "Résumé hebdomadaire disponible."
            for member in project.members:
                send_notification(
                    user_id=member.id,
                    title=title,
                    content=content[:500],
                    notif_type="ai_weekly_summary",
                    link=f"/projects/{project.id}",
                )
                db.session.add(
                    AIUsageLog(
                        project_id=project.id,
                        user_id=member.id,
                        endpoint="weekly-summary-cron",
                        status="success",
                        response_json=json.dumps(summary_data, ensure_ascii=False),
                    )
                )
            db.session.commit()
        except AIServiceError as exc:
            db.session.add(
                AIUsageLog(
                    project_id=project.id,
                    user_id=None,
                    endpoint="weekly-summary-cron",
                    status="failed",
                    error=str(exc),
                )
            )
            db.session.commit()


def _previous_month_label() -> str:
    first_day_current = date.today().replace(day=1)
    prev_month_last_day = first_day_current - timedelta(days=1)
    return prev_month_last_day.strftime("%Y-%m")


def run_monthly_payroll_job():
    month_label = _previous_month_label()
    projects = Project.query.all()
    for project in projects:
        generate_payroll_for_project(
            project=project,
            generated_by_id=None,
            month=month_label,
            base_amount=100000.0,
            bonus_per_validated=2000.0,
            penalty_per_rejected=1000.0,
            penalty_per_overdue=1500.0,
            currency="XOF",
            notes=f"Auto-generated by scheduler for {month_label}",
        )


def start_scheduler(app):
    global _scheduler
    if _scheduler is not None:
        return _scheduler

    if not app.config.get("AI_WEEKLY_SUMMARY_SCHEDULER_ENABLED", True):
        return None

    scheduler = BackgroundScheduler(timezone="UTC")

    def _wrapped_job():
        with app.app_context():
            run_weekly_summaries_job()

    scheduler.add_job(
        _wrapped_job,
        trigger="cron",
        day_of_week=app.config.get("AI_WEEKLY_SUMMARY_CRON_DAY", "mon"),
        hour=app.config.get("AI_WEEKLY_SUMMARY_CRON_HOUR", 8),
        minute=app.config.get("AI_WEEKLY_SUMMARY_CRON_MINUTE", 0),
        id="weekly_ai_summary_job",
        replace_existing=True,
    )

    if app.config.get("PAYROLL_MONTHLY_SCHEDULER_ENABLED", True):
        def _wrapped_payroll_job():
            with app.app_context():
                run_monthly_payroll_job()

        scheduler.add_job(
            _wrapped_payroll_job,
            trigger="cron",
            day=app.config.get("PAYROLL_MONTHLY_CRON_DAY", 1),
            hour=app.config.get("PAYROLL_MONTHLY_CRON_HOUR", 1),
            minute=app.config.get("PAYROLL_MONTHLY_CRON_MINUTE", 0),
            id="monthly_payroll_job",
            replace_existing=True,
        )
    scheduler.start()
    _scheduler = scheduler
    return _scheduler
