"""Initial migration

Revision ID: cc671ed40ebe
Revises: b9c0d1e2f3a4
Create Date: 2026-04-13 14:53:05.582336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc671ed40ebe'
down_revision = 'b9c0d1e2f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_logs_user_id'))

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))

    with op.batch_alter_table('chat_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_attachments_project_id'))

    with op.batch_alter_table('sync_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_operations_created_at'))
        batch_op.drop_index(batch_op.f('ix_sync_operations_project_id'))
        batch_op.drop_index(batch_op.f('ix_sync_operations_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_operations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_operations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_operations_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('chat_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_attachments_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('ai_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_logs_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
