"""add invitations table

Revision ID: d61d19b48413
Revises: b5c6d7e8f9a0
Create Date: 2026-05-18 18:48:44.091567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd61d19b48413'
down_revision = 'b5c6d7e8f9a0'
branch_labels = None
depends_on = None


def upgrade():
    # Use raw DDL so we don't touch the existing 'memberrole' enum type.
    # 'invitationstatus' is brand-new — create it first (idempotent).
    op.execute(sa.text(
        "DO $$ BEGIN "
        "  CREATE TYPE invitationstatus AS ENUM ('pending','accepted','expired','cancelled'); "
        "EXCEPTION WHEN duplicate_object THEN null; "
        "END $$;"
    ))

    op.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS invitations (
            id               SERIAL          PRIMARY KEY,
            token            VARCHAR(64)     NOT NULL,
            project_id       INTEGER         NOT NULL
                REFERENCES projects(id) ON DELETE CASCADE,
            invited_email    VARCHAR(150)    NOT NULL,
            role             memberrole      NOT NULL DEFAULT 'member',
            invited_by_id    INTEGER
                REFERENCES users(id) ON DELETE SET NULL,
            contract_title   VARCHAR(200),
            contract_content TEXT,
            status           invitationstatus NOT NULL DEFAULT 'pending',
            expires_at       TIMESTAMP       NOT NULL,
            created_at       TIMESTAMP       DEFAULT NOW()
        )
    """))

    op.execute(sa.text(
        "CREATE UNIQUE INDEX IF NOT EXISTS ix_invitations_token ON invitations(token)"
    ))

    op.drop_table('user_task_rewards')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_task_rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('user_task_rewards_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_task_rewards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_task_rewards_pkey')),
    sa.UniqueConstraint('user_id', 'task_id', 'reward_type', name=op.f('uq_user_task_reward_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))

    op.drop_table('invitations')
    # ### end Alembic commands ###
