"""add color_theme icon slug to projects

Revision ID: df4b36f6d205
Revises: a1c2e3f4b5d6
Create Date: 2026-06-01 21:49:05.532362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4b36f6d205'
down_revision = 'a1c2e3f4b5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_theme', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=10), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('slug')
        batch_op.drop_column('icon')
        batch_op.drop_column('color_theme')

    # ### end Alembic commands ###
